// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Reducer$ProbabilityDashboard = require("../reducers/Reducer.bs.js");
var StateProviderRaw$ProbabilityDashboard = require("./StateProviderRaw.bs.js");

function StateProvider(Props) {
  var children = Props.children;
  return React.createElement(StateProviderRaw$ProbabilityDashboard.make, StateProviderRaw$ProbabilityDashboard.makeProps(React.useReducer(Reducer$ProbabilityDashboard.rootReducer, Reducer$ProbabilityDashboard.initialState), children, /* () */0));
}

var make = StateProvider;

exports.make = make;
/* react Not a pure module */
