// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var stateContext = React.createContext(undefined);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = stateContext.Provider;

var c = undefined;

exports.c = c;
exports.stateContext = stateContext;
exports.makeProps = makeProps;
exports.make = make;
/* stateContext Not a pure module */
