// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var StateProviderRaw$ProbabilityDashboard = require("../providers/StateProviderRaw.bs.js");

function useStateValue(param) {
  return React.useContext(StateProviderRaw$ProbabilityDashboard.stateContext);
}

exports.useStateValue = useStateValue;
/* react Not a pure module */
