// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function rootReducer(state, action) {
  return /* record */[/* value */state[/* value */0] + action[0] | 0];
}

var initialState = /* record */[/* value */1];

exports.initialState = initialState;
exports.rootReducer = rootReducer;
/* No side effect */
