// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Hooks$ProbabilityDashboard = require("../hooks/Hooks.bs.js");

function Panel(Props) {
  var match = Hooks$ProbabilityDashboard.useStateValue(/* () */0);
  var dispatch = match[1];
  var increaseValue = function (param) {
    return Curry._1(dispatch, /* Add */[1]);
  };
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: increaseValue
                }, "Add more 1"));
}

var make = Panel;

exports.make = make;
/* react Not a pure module */
