// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Hooks$ProbabilityDashboard = require("../hooks/Hooks.bs.js");

function Stats(Props) {
  var match = Hooks$ProbabilityDashboard.useStateValue(/* () */0);
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Stats"), React.createElement("p", undefined, String(match[0][/* value */0])));
}

var make = Stats;

exports.make = make;
/* react Not a pure module */
