// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ProbabilityDashboard = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ProbabilityDashboard.make, {
          message: "Hello! Click this text."
        }), "root");

/*  Not a pure module */
